baseURL = "https://pavelnikolov.net/"
canonifyURLs = true
copyright = "2017 Pavel Nikolov. All rights reserved."
disqusShortname = "pavelnikolov"
googleAnalytics = "UA-29424849-1"
languageCode = "en-us"
theme = "hugo-zen"
title = "Pavel Nikolov's blog"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Pavel Nikolov's blog"
  author = "Pavel Nikolov"
  logo      = "/images/pavel-nikolov.jpg"
  twitter   = "https://twitter.com/pavelnikolov"
  facebook  = "https://www.facebook.com/medunchoto"
  github    = "https://github.com/pavelnikolov"

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]