baseURL = 'https://pavelnikolov.net/'
locale = 'en-us'
title = 'Pavel Nikolov'
enableRobotsTXT = true

[params]
	description = 'Personal website and blog of Pavel Nikolov.'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.parser.attribute]
    block = true

[menu]
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Blog'
		pageRef = '/blog'
		weight = 20
	[[menu.main]]
		name = 'Talks'
		pageRef = '/talks'
		weight = 30
